// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using incode.Models;

#nullable disable

namespace incode.Migrations
{
    [DbContext(typeof(incodedatabaseContext))]
    [Migration("20251215040856_TableMoviecolumntitle")]
    partial class TableMoviecolumntitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("incode.Models.Admin", b =>
                {
                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<int?>("Autority")
                        .HasColumnType("int")
                        .HasColumnName("autority");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("type");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("incode.Models.Cinema", b =>
                {
                    b.Property<int>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cinema_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinemaId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chain");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district");

                    b.Property<string>("Facilities")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("facilities");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("website");

                    b.HasKey("CinemaId")
                        .HasName("PK__cinemas__5662877858C3321B");

                    b.HasIndex(new[] { "City" }, "idx_city");

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "idx_location");

                    b.ToTable("cinemas", (string)null);
                });

            modelBuilder.Entity("incode.Models.CinemaReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("cinema_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("EnvironmentRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("environment_rating");

                    b.Property<int?>("HelpfulCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("helpful_count");

                    b.Property<int?>("LinkedPostId")
                        .HasColumnType("int")
                        .HasColumnName("linked_post_id");

                    b.Property<string>("MovieWatched")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("movie_watched");

                    b.Property<decimal?>("PriceRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("price_rating");

                    b.Property<decimal?>("ScreenRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("screen_rating");

                    b.Property<decimal?>("SeatRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("seat_rating");

                    b.Property<decimal?>("ServiceRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("service_rating");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.HasKey("ReviewId")
                        .HasName("PK__cinema_r__60883D90C38AB1FA");

                    b.HasIndex("CinemaId");

                    b.HasIndex("LinkedPostId");

                    b.HasIndex("UserId");

                    b.ToTable("cinema_reviews", (string)null);
                });

            modelBuilder.Entity("incode.Models.EntrustMission", b =>
                {
                    b.Property<int>("EntrustMissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entrust_mission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrustMissionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("detail");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int")
                        .HasColumnName("reward_points");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EntrustMissionId")
                        .HasName("PK__entrust___19471E9515C1AB86");

                    b.HasIndex("UserId");

                    b.ToTable("entrust_mission", (string)null);
                });

            modelBuilder.Entity("incode.Models.EntrustMissionProgress", b =>
                {
                    b.Property<int>("EntrustMissionProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entrust_mission_progress_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrustMissionProgressId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EntrustMissionId")
                        .HasColumnType("int")
                        .HasColumnName("entrust_mission_id");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_completed")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("accepted")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EntrustMissionProgressId")
                        .HasName("PK__entrust___8F68D7F47425446F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "EntrustMissionId", "UserId" }, "entrust_mission_progress_index_2")
                        .IsUnique();

                    b.ToTable("entrust_mission_progress", (string)null);
                });

            modelBuilder.Entity("incode.Models.Follow", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int")
                        .HasColumnName("follower_id");

                    b.Property<int>("FolloweeId")
                        .HasColumnType("int")
                        .HasColumnName("followee_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FollowerId", "FolloweeId")
                        .HasName("PK__follows__710D19E636F1C339");

                    b.HasIndex("FolloweeId");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("incode.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("caption");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ImageId")
                        .HasName("PK__images__DC9AC955DE475D8F");

                    b.HasIndex("UserId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("incode.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MissionDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mission_detail");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mission_name");

                    b.Property<string>("ResetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("none")
                        .HasColumnName("reset_type");

                    b.Property<int>("RewardExp")
                        .HasColumnType("int")
                        .HasColumnName("reward_exp");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int")
                        .HasColumnName("reward_points");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int")
                        .HasColumnName("target_count");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("target_type");

                    b.HasKey("MissionId")
                        .HasName("PK__mission__B5419AB28922714E");

                    b.ToTable("mission", (string)null);
                });

            modelBuilder.Entity("incode.Models.MissionProgress", b =>
                {
                    b.Property<int>("MissionProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mission_progress_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionProgressId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int")
                        .HasColumnName("current_count");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_completed")
                        .HasDefaultValueSql("('0')");

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MissionProgressId")
                        .HasName("PK__mission___F43E603D4DB2CE0E");

                    b.HasIndex("MissionId");

                    b.HasIndex(new[] { "UserId", "MissionId" }, "mission_progress_index_1")
                        .IsUnique();

                    b.ToTable("mission_progress", (string)null);
                });

            modelBuilder.Entity("incode.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("director");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("genre");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("original_title");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("poster_url");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("rating");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("synopsis");

                    b.Property<int>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("int")
                        .HasColumnName("title");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("trailer_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MovieId")
                        .HasName("PK__movies__83CDF74926567634");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("incode.Models.MovieReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<decimal?>("ActingRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("acting_rating");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("HelpfulCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("helpful_count");

                    b.Property<bool?>("IsSpoiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_spoiler");

                    b.Property<int?>("LinkedPostId")
                        .HasColumnType("int")
                        .HasColumnName("linked_post_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<decimal?>("MusicRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("music_rating");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("overall_rating");

                    b.Property<decimal?>("StoryRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("story_rating");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<decimal?>("VisualRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("visual_rating");

                    b.HasKey("ReviewId")
                        .HasName("PK__movie_re__60883D9059F97F9B");

                    b.HasIndex("LinkedPostId");

                    b.HasIndex(new[] { "MovieId" }, "idx_movie");

                    b.HasIndex(new[] { "OverallRating" }, "idx_rating");

                    b.HasIndex(new[] { "UserId" }, "idx_user");

                    b.HasIndex(new[] { "MovieId", "UserId" }, "movie_reviews_index_2")
                        .IsUnique();

                    b.ToTable("movie_reviews", (string)null);
                });

            modelBuilder.Entity("incode.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("RequiresShipping")
                        .HasColumnType("bit")
                        .HasColumnName("requires_shipping");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("total_price");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__order__46596229014D95EC");

                    b.HasIndex("UserId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("incode.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<bool>("IsShipped")
                        .HasColumnType("bit")
                        .HasColumnName("is_shipped");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("UnitPriceAtPurchase")
                        .HasColumnType("int")
                        .HasColumnName("unit_price_at_purchase");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__order_de__3C5A4080663AB9A6");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_detail", (string)null);
                });

            modelBuilder.Entity("incode.Models.PointLog", b =>
                {
                    b.Property<int>("PointLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("point_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointLogId"));

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("int")
                        .HasColumnName("change_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("unknow")
                        .HasColumnName("description");

                    b.Property<int>("PointTypeDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("point_type_definition_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PointLogId")
                        .HasName("PK__point_lo__E2EBFE7C152E2E06");

                    b.HasIndex("PointTypeDefinitionId");

                    b.HasIndex("UserId");

                    b.ToTable("point_log", (string)null);
                });

            modelBuilder.Entity("incode.Models.PointPurchaseLog", b =>
                {
                    b.Property<int>("PointPurchaseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("point_purchase_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointPurchaseLogId"));

                    b.Property<decimal>("CashAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("cash_amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("order_no");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PointsAmount")
                        .HasColumnType("int")
                        .HasColumnName("points_amount");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PointPurchaseLogId")
                        .HasName("PK__point_pu__134871228085866B");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrderNo" }, "UQ__point_pu__465C81B81B35C2DD")
                        .IsUnique();

                    b.ToTable("point_purchase_log", (string)null);
                });

            modelBuilder.Entity("incode.Models.PointTypeDefinition", b =>
                {
                    b.Property<int>("PointTypeDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("point_type_definition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointTypeDefinitionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("PointTypeDefinitionId")
                        .HasName("PK__point_ty__E69D541F8B2CA7DC");

                    b.HasIndex(new[] { "TypeName" }, "UQ__point_ty__543C4FD940BBCD54")
                        .IsUnique();

                    b.ToTable("point_type_definition", (string)null);
                });

            modelBuilder.Entity("incode.Models.Post", b =>
                {
                    b.Property<int>("PostsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("posts_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostsId"));

                    b.Property<bool>("IsCommission")
                        .HasColumnType("bit");

                    b.Property<string>("PostsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("posts_content");

                    b.Property<DateTime?>("PostsCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("posts_created_at");

                    b.Property<DateTime?>("PostsUpdatDate")
                        .HasColumnType("datetime")
                        .HasColumnName("posts_updat_date");

                    b.Property<int>("PostsUserId")
                        .HasColumnType("int")
                        .HasColumnName("posts_user_id");

                    b.Property<int?>("PostsViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("posts_view_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("PostsId")
                        .HasName("PK__posts__7F3EFABE1C8EE550");

                    b.HasIndex("PostsUserId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("incode.Models.PostReplyLike", b =>
                {
                    b.Property<int>("ReplyLikesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reply_likes_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyLikesId"));

                    b.Property<int>("ReplyIkesId")
                        .HasColumnType("int")
                        .HasColumnName("reply_ikes_id");

                    b.Property<DateTime?>("ReplyLikesCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reply_likes_created_at");

                    b.Property<int>("ReplyLikesUserId")
                        .HasColumnType("int")
                        .HasColumnName("reply_likes_user_id");

                    b.HasKey("ReplyLikesId")
                        .HasName("PK__post_rep__BA01D0E784F6B6CC");

                    b.HasIndex("ReplyIkesId");

                    b.HasIndex("ReplyLikesUserId");

                    b.HasIndex(new[] { "ReplyLikesId", "ReplyLikesUserId" }, "post_reply_likes_index_10")
                        .IsUnique();

                    b.ToTable("post_reply_likes", (string)null);
                });

            modelBuilder.Entity("incode.Models.PostsLike", b =>
                {
                    b.Property<int>("LikesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("likes_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikesId"));

                    b.Property<DateTime?>("LikesCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("likes_created_at");

                    b.Property<int>("LikesUserId")
                        .HasColumnType("int")
                        .HasColumnName("likes_user_id");

                    b.Property<int>("PostsLikesId")
                        .HasColumnType("int")
                        .HasColumnName("posts_likes_id");

                    b.HasKey("LikesId")
                        .HasName("PK__posts_li__0CA5EC54D5C208D2");

                    b.HasIndex("LikesUserId");

                    b.HasIndex(new[] { "PostsLikesId", "LikesUserId" }, "posts_likes_index_9")
                        .IsUnique();

                    b.ToTable("posts_likes", (string)null);
                });

            modelBuilder.Entity("incode.Models.PostsReply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reply_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"));

                    b.Property<string>("RepliesContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("replies_content");

                    b.Property<DateTime?>("RepliesCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("replies_created_at");

                    b.Property<int>("RepliesPostId")
                        .HasColumnType("int")
                        .HasColumnName("replies_post_id");

                    b.Property<int>("RepliesUserId")
                        .HasColumnType("int")
                        .HasColumnName("replies_user_id");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int")
                        .HasColumnName("target_user_id");

                    b.HasKey("ReplyId")
                        .HasName("PK__posts_re__EE405698AB031DA3");

                    b.HasIndex("RepliesPostId");

                    b.HasIndex("RepliesUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("posts_replies", (string)null);
                });

            modelBuilder.Entity("incode.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImageName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_name");

                    b.Property<bool>("IsOnSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_on_sale");

                    b.Property<bool>("IsPhysical")
                        .HasColumnType("bit")
                        .HasColumnName("is_physical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ProductId")
                        .HasName("PK__product__47027DF5D3AE3345");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("incode.Models.ReviewHelpfulVote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vote_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("bit")
                        .HasColumnName("is_helpful");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("review_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("VoteId")
                        .HasName("PK__review_h__9F5405AE9574994C");

                    b.HasIndex("UserId");

                    b.ToTable("review_helpful_votes", (string)null);
                });

            modelBuilder.Entity("incode.Models.SavePost", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("save_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaveId"));

                    b.Property<DateTime?>("SaveCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("save_created_at");

                    b.Property<int>("SavePostsId")
                        .HasColumnType("int")
                        .HasColumnName("save_posts_id");

                    b.Property<int>("SaveUserId")
                        .HasColumnType("int")
                        .HasColumnName("save_user_id");

                    b.HasKey("SaveId")
                        .HasName("PK__save_pos__319269DE7F623BE0");

                    b.HasIndex("SavePostsId");

                    b.HasIndex(new[] { "SaveUserId", "SavePostsId" }, "save_posts_index_8")
                        .IsUnique();

                    b.ToTable("save_posts", (string)null);
                });

            modelBuilder.Entity("incode.Models.ShippedDetail", b =>
                {
                    b.Property<int>("ShippedDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipped_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippedDetailId"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recipient_address");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recipient_phone");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("shipped_date");

                    b.HasKey("ShippedDetailId")
                        .HasName("PK__shipped___26C93C9342E38DFB");

                    b.HasIndex("OrderDetailId");

                    b.ToTable("shipped_detail", (string)null);
                });

            modelBuilder.Entity("incode.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int?>("Phone")
                        .HasColumnType("int")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__user__B9BE370F6AA687F6");

                    b.HasIndex(new[] { "Nickname" }, "UQ__user__5CF1C59B3264F725")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("incode.Models.UserLogin", b =>
                {
                    b.Property<string>("Loction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("loction");

                    b.Property<DateTime?>("Logintime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("logintime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("incode.Models.UserMovieList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<decimal?>("PersonalRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("personal_rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("WatchDate")
                        .HasColumnType("date")
                        .HasColumnName("watch_date");

                    b.HasKey("ListId")
                        .HasName("PK__user_mov__7B9EF135F96DF46B");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("user_movie_list", (string)null);
                });

            modelBuilder.Entity("incode.Models.UserStatus", b =>
                {
                    b.Property<int?>("Experience")
                        .HasColumnType("int")
                        .HasColumnName("experience");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId");

                    b.ToTable("user_status", (string)null);
                });

            modelBuilder.Entity("incode.Models.WalletTransaction", b =>
                {
                    b.Property<int>("WalletTransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wallet_transactions_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletTransactionsId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RelatedOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("related_order_id");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("transaction_status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WalletTransactionsId")
                        .HasName("PK__wallet_t__54E8436663D419C3");

                    b.HasIndex("UserId");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("incode.Models.CinemaReview", b =>
                {
                    b.HasOne("incode.Models.Cinema", "Cinema")
                        .WithMany("CinemaReviews")
                        .HasForeignKey("CinemaId")
                        .IsRequired()
                        .HasConstraintName("FK__cinema_re__cinem__22751F6C");

                    b.HasOne("incode.Models.Post", "LinkedPost")
                        .WithMany("CinemaReviews")
                        .HasForeignKey("LinkedPostId")
                        .HasConstraintName("FK__cinema_re__linke__236943A5");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("CinemaReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__cinema_re__user___2180FB33");

                    b.Navigation("Cinema");

                    b.Navigation("LinkedPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.EntrustMission", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("EntrustMissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__entrust_m__user___32AB8735");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.EntrustMissionProgress", b =>
                {
                    b.HasOne("incode.Models.EntrustMission", "EntrustMission")
                        .WithMany("EntrustMissionProgresses")
                        .HasForeignKey("EntrustMissionId")
                        .IsRequired()
                        .HasConstraintName("FK__entrust_m__entru__30C33EC3");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("EntrustMissionProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__entrust_m__user___339FAB6E");

                    b.Navigation("EntrustMission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.Follow", b =>
                {
                    b.HasOne("incode.Models.User", "Followee")
                        .WithMany("FollowFollowees")
                        .HasForeignKey("FolloweeId")
                        .IsRequired()
                        .HasConstraintName("FK__follows__followe__29221CFB");

                    b.HasOne("incode.Models.User", "Follower")
                        .WithMany("FollowFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("FK__follows__followe__282DF8C2");

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("incode.Models.Image", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__images__user_id__2739D489");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.MissionProgress", b =>
                {
                    b.HasOne("incode.Models.Mission", "Mission")
                        .WithMany("MissionProgresses")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK__mission_p__missi__2CF2ADDF");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("MissionProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__mission_p__user___31B762FC");

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.MovieReview", b =>
                {
                    b.HasOne("incode.Models.Post", "LinkedPost")
                        .WithMany("MovieReviews")
                        .HasForeignKey("LinkedPostId")
                        .HasConstraintName("FK__movie_rev__linke__208CD6FA");

                    b.HasOne("incode.Models.Movie", "Movie")
                        .WithMany("MovieReviews")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__movie_rev__movie__1F98B2C1");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("MovieReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__movie_rev__user___1EA48E88");

                    b.Navigation("LinkedPost");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.Order", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__order__user_id__3493CFA7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.OrderDetail", b =>
                {
                    b.HasOne("incode.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__order_det__order__3587F3E0");

                    b.HasOne("incode.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__order_det__produ__367C1819");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("incode.Models.PointLog", b =>
                {
                    b.HasOne("incode.Models.PointTypeDefinition", "PointTypeDefinition")
                        .WithMany("PointLogs")
                        .HasForeignKey("PointTypeDefinitionId")
                        .IsRequired()
                        .HasConstraintName("FK__point_log__point__2EDAF651");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("PointLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__point_log__user___2BFE89A6");

                    b.Navigation("PointTypeDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.PointPurchaseLog", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("PointPurchaseLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__point_pur__user___2DE6D218");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.Post", b =>
                {
                    b.HasOne("incode.Models.User", "PostsUser")
                        .WithMany("Posts")
                        .HasForeignKey("PostsUserId")
                        .IsRequired()
                        .HasConstraintName("FK__posts__posts_use__3864608B");

                    b.Navigation("PostsUser");
                });

            modelBuilder.Entity("incode.Models.PostReplyLike", b =>
                {
                    b.HasOne("incode.Models.PostsReply", "ReplyIkes")
                        .WithMany("PostReplyLikes")
                        .HasForeignKey("ReplyIkesId")
                        .IsRequired()
                        .HasConstraintName("FK__post_repl__reply__40F9A68C");

                    b.HasOne("incode.Models.User", "ReplyLikesUser")
                        .WithMany("PostReplyLikes")
                        .HasForeignKey("ReplyLikesUserId")
                        .IsRequired()
                        .HasConstraintName("FK__post_repl__reply__3D2915A8");

                    b.Navigation("ReplyIkes");

                    b.Navigation("ReplyLikesUser");
                });

            modelBuilder.Entity("incode.Models.PostsLike", b =>
                {
                    b.HasOne("incode.Models.User", "LikesUser")
                        .WithMany("PostsLikes")
                        .HasForeignKey("LikesUserId")
                        .IsRequired()
                        .HasConstraintName("FK__posts_lik__likes__3C34F16F");

                    b.HasOne("incode.Models.Post", "PostsLikes")
                        .WithMany("PostsLikes")
                        .HasForeignKey("PostsLikesId")
                        .IsRequired()
                        .HasConstraintName("FK__posts_lik__posts__40058253");

                    b.Navigation("LikesUser");

                    b.Navigation("PostsLikes");
                });

            modelBuilder.Entity("incode.Models.PostsReply", b =>
                {
                    b.HasOne("incode.Models.Post", "RepliesPost")
                        .WithMany("PostsReplies")
                        .HasForeignKey("RepliesPostId")
                        .IsRequired()
                        .HasConstraintName("FK__posts_rep__repli__3F115E1A");

                    b.HasOne("incode.Models.User", "RepliesUser")
                        .WithMany("PostsReplyRepliesUsers")
                        .HasForeignKey("RepliesUserId")
                        .IsRequired()
                        .HasConstraintName("FK__posts_rep__repli__3A4CA8FD");

                    b.HasOne("incode.Models.User", "TargetUser")
                        .WithMany("PostsReplyTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK__posts_rep__targe__3B40CD36");

                    b.Navigation("RepliesPost");

                    b.Navigation("RepliesUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("incode.Models.ReviewHelpfulVote", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("ReviewHelpfulVotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__review_he__user___245D67DE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.SavePost", b =>
                {
                    b.HasOne("incode.Models.Post", "SavePosts")
                        .WithMany("SavePosts")
                        .HasForeignKey("SavePostsId")
                        .IsRequired()
                        .HasConstraintName("FK__save_post__save___3E1D39E1");

                    b.HasOne("incode.Models.User", "SaveUser")
                        .WithMany("SavePosts")
                        .HasForeignKey("SaveUserId")
                        .IsRequired()
                        .HasConstraintName("FK__save_post__save___395884C4");

                    b.Navigation("SavePosts");

                    b.Navigation("SaveUser");
                });

            modelBuilder.Entity("incode.Models.ShippedDetail", b =>
                {
                    b.HasOne("incode.Models.OrderDetail", "OrderDetail")
                        .WithMany("ShippedDetails")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__shipped_d__order__37703C52");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("incode.Models.UserLogin", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_logi__user___2B0A656D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.UserMovieList", b =>
                {
                    b.HasOne("incode.Models.Movie", "Movie")
                        .WithMany("UserMovieLists")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__user_movi__movie__2645B050");

                    b.HasOne("incode.Models.User", "User")
                        .WithMany("UserMovieLists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__user_movi__user___25518C17");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.UserStatus", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__user_stat__user___2A164134");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.WalletTransaction", b =>
                {
                    b.HasOne("incode.Models.User", "User")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__wallet_tr__user___2FCF1A8A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("incode.Models.Cinema", b =>
                {
                    b.Navigation("CinemaReviews");
                });

            modelBuilder.Entity("incode.Models.EntrustMission", b =>
                {
                    b.Navigation("EntrustMissionProgresses");
                });

            modelBuilder.Entity("incode.Models.Mission", b =>
                {
                    b.Navigation("MissionProgresses");
                });

            modelBuilder.Entity("incode.Models.Movie", b =>
                {
                    b.Navigation("MovieReviews");

                    b.Navigation("UserMovieLists");
                });

            modelBuilder.Entity("incode.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("incode.Models.OrderDetail", b =>
                {
                    b.Navigation("ShippedDetails");
                });

            modelBuilder.Entity("incode.Models.PointTypeDefinition", b =>
                {
                    b.Navigation("PointLogs");
                });

            modelBuilder.Entity("incode.Models.Post", b =>
                {
                    b.Navigation("CinemaReviews");

                    b.Navigation("MovieReviews");

                    b.Navigation("PostsLikes");

                    b.Navigation("PostsReplies");

                    b.Navigation("SavePosts");
                });

            modelBuilder.Entity("incode.Models.PostsReply", b =>
                {
                    b.Navigation("PostReplyLikes");
                });

            modelBuilder.Entity("incode.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("incode.Models.User", b =>
                {
                    b.Navigation("CinemaReviews");

                    b.Navigation("EntrustMissionProgresses");

                    b.Navigation("EntrustMissions");

                    b.Navigation("FollowFollowees");

                    b.Navigation("FollowFollowers");

                    b.Navigation("Images");

                    b.Navigation("MissionProgresses");

                    b.Navigation("MovieReviews");

                    b.Navigation("Orders");

                    b.Navigation("PointLogs");

                    b.Navigation("PointPurchaseLogs");

                    b.Navigation("PostReplyLikes");

                    b.Navigation("Posts");

                    b.Navigation("PostsLikes");

                    b.Navigation("PostsReplyRepliesUsers");

                    b.Navigation("PostsReplyTargetUsers");

                    b.Navigation("ReviewHelpfulVotes");

                    b.Navigation("SavePosts");

                    b.Navigation("UserMovieLists");

                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
