// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Admin
{
    public int? AdminId { get; set; }

    public string Type { get; set; }

    public int? Autority { get; set; }
}