// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class CinemaReview
{
    public int ReviewId { get; set; }

    public int CinemaId { get; set; }

    public int UserId { get; set; }

    public decimal? SeatRating { get; set; }

    public decimal? ScreenRating { get; set; }

    public decimal? ServiceRating { get; set; }

    public decimal? EnvironmentRating { get; set; }

    public decimal? PriceRating { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateOnly? VisitDate { get; set; }

    public string MovieWatched { get; set; }

    public int? HelpfulCount { get; set; }

    public int? ViewCount { get; set; }

    public int? LinkedPostId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Cinema Cinema { get; set; }

    public virtual Post LinkedPost { get; set; }

    public virtual User User { get; set; }
}