// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Cinema
{
    public int CinemaId { get; set; }

    public string Name { get; set; }

    public string Chain { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public string Facilities { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CinemaReview> CinemaReviews { get; set; } = new List<CinemaReview>();
}