// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class EntrustMission
{
    public int EntrustMissionId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Detail { get; set; }

    public int RewardPoints { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<EntrustMissionProgress> EntrustMissionProgresses { get; set; } = new List<EntrustMissionProgress>();

    public virtual User User { get; set; }
}