// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class EntrustMissionProgress
{
    public int EntrustMissionProgressId { get; set; }

    public int UserId { get; set; }

    public int EntrustMissionId { get; set; }

    public string Status { get; set; }

    public bool? IsCompleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual EntrustMission EntrustMission { get; set; }

    public virtual User User { get; set; }
}