// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Follow
{
    public int FollowerId { get; set; }

    public int FolloweeId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Followee { get; set; }

    public virtual User Follower { get; set; }
}