// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public int UserId { get; set; }

    public string ImageUrl { get; set; }

    public int Category { get; set; }

    public string Caption { get; set; }

    public int? DisplayOrder { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}