// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace incode.Models;

public partial class incodedatabaseContext : DbContext
{
    public incodedatabaseContext(DbContextOptions<incodedatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Cinema> Cinemas { get; set; }

    public virtual DbSet<CinemaReview> CinemaReviews { get; set; }

    public virtual DbSet<EntrustMission> EntrustMissions { get; set; }

    public virtual DbSet<EntrustMissionProgress> EntrustMissionProgresses { get; set; }

    public virtual DbSet<Follow> Follows { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<Mission> Missions { get; set; }

    public virtual DbSet<MissionProgress> MissionProgresses { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<MovieReview> MovieReviews { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<PointLog> PointLogs { get; set; }

    public virtual DbSet<PointPurchaseLog> PointPurchaseLogs { get; set; }

    public virtual DbSet<PointTypeDefinition> PointTypeDefinitions { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostReplyLike> PostReplyLikes { get; set; }

    public virtual DbSet<PostsLike> PostsLikes { get; set; }

    public virtual DbSet<PostsReply> PostsReplies { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ReviewHelpfulVote> ReviewHelpfulVotes { get; set; }

    public virtual DbSet<SavePost> SavePosts { get; set; }

    public virtual DbSet<ShippedDetail> ShippedDetails { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserLogin> UserLogins { get; set; }

    public virtual DbSet<UserMovieList> UserMovieLists { get; set; }

    public virtual DbSet<UserStatus> UserStatuses { get; set; }

    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("admin");

            entity.Property(e => e.AdminId).HasColumnName("admin_id");
            entity.Property(e => e.Autority).HasColumnName("autority");
            entity.Property(e => e.Type)
                .HasMaxLength(255)
                .HasColumnName("type");
        });

        modelBuilder.Entity<Cinema>(entity =>
        {
            entity.HasKey(e => e.CinemaId).HasName("PK__cinemas__5662877858C3321B");

            entity.ToTable("cinemas");

            entity.HasIndex(e => e.City, "idx_city");

            entity.HasIndex(e => new { e.Latitude, e.Longitude }, "idx_location");

            entity.Property(e => e.CinemaId).HasColumnName("cinema_id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("address");
            entity.Property(e => e.Chain)
                .HasMaxLength(50)
                .HasColumnName("chain");
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .HasColumnName("city");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.District)
                .HasMaxLength(50)
                .HasColumnName("district");
            entity.Property(e => e.Facilities)
                .HasMaxLength(500)
                .HasColumnName("facilities");
            entity.Property(e => e.Latitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Website)
                .HasMaxLength(200)
                .HasColumnName("website");
        });

        modelBuilder.Entity<CinemaReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__cinema_r__60883D90C38AB1FA");

            entity.ToTable("cinema_reviews");

            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.CinemaId).HasColumnName("cinema_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EnvironmentRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("environment_rating");
            entity.Property(e => e.HelpfulCount)
                .HasDefaultValue(0)
                .HasColumnName("helpful_count");
            entity.Property(e => e.LinkedPostId).HasColumnName("linked_post_id");
            entity.Property(e => e.MovieWatched)
                .HasMaxLength(200)
                .HasColumnName("movie_watched");
            entity.Property(e => e.PriceRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("price_rating");
            entity.Property(e => e.ScreenRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("screen_rating");
            entity.Property(e => e.SeatRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("seat_rating");
            entity.Property(e => e.ServiceRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("service_rating");
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.ViewCount)
                .HasDefaultValue(0)
                .HasColumnName("view_count");
            entity.Property(e => e.VisitDate).HasColumnName("visit_date");

            entity.HasOne(d => d.Cinema).WithMany(p => p.CinemaReviews)
                .HasForeignKey(d => d.CinemaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cinema_re__cinem__22751F6C");

            entity.HasOne(d => d.LinkedPost).WithMany(p => p.CinemaReviews)
                .HasForeignKey(d => d.LinkedPostId)
                .HasConstraintName("FK__cinema_re__linke__236943A5");

            entity.HasOne(d => d.User).WithMany(p => p.CinemaReviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cinema_re__user___2180FB33");
        });

        modelBuilder.Entity<EntrustMission>(entity =>
        {
            entity.HasKey(e => e.EntrustMissionId).HasName("PK__entrust___19471E9515C1AB86");

            entity.ToTable("entrust_mission");

            entity.Property(e => e.EntrustMissionId).HasColumnName("entrust_mission_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Detail)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("detail");
            entity.Property(e => e.RewardPoints).HasColumnName("reward_points");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("open")
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("title");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.EntrustMissions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__entrust_m__user___32AB8735");
        });

        modelBuilder.Entity<EntrustMissionProgress>(entity =>
        {
            entity.HasKey(e => e.EntrustMissionProgressId).HasName("PK__entrust___8F68D7F47425446F");

            entity.ToTable("entrust_mission_progress");

            entity.HasIndex(e => new { e.EntrustMissionId, e.UserId }, "entrust_mission_progress_index_2").IsUnique();

            entity.Property(e => e.EntrustMissionProgressId).HasColumnName("entrust_mission_progress_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EntrustMissionId).HasColumnName("entrust_mission_id");
            entity.Property(e => e.IsCompleted)
                .HasDefaultValueSql("('0')")
                .HasColumnName("is_completed");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("accepted")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.EntrustMission).WithMany(p => p.EntrustMissionProgresses)
                .HasForeignKey(d => d.EntrustMissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__entrust_m__entru__30C33EC3");

            entity.HasOne(d => d.User).WithMany(p => p.EntrustMissionProgresses)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__entrust_m__user___339FAB6E");
        });

        modelBuilder.Entity<Follow>(entity =>
        {
            entity.HasKey(e => new { e.FollowerId, e.FolloweeId }).HasName("PK__follows__710D19E636F1C339");

            entity.ToTable("follows");

            entity.Property(e => e.FollowerId).HasColumnName("follower_id");
            entity.Property(e => e.FolloweeId).HasColumnName("followee_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.Followee).WithMany(p => p.FollowFollowees)
                .HasForeignKey(d => d.FolloweeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__follows__followe__29221CFB");

            entity.HasOne(d => d.Follower).WithMany(p => p.FollowFollowers)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__follows__followe__282DF8C2");
        });

        modelBuilder.Entity<Image>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__images__DC9AC955DE475D8F");

            entity.ToTable("images");

            entity.Property(e => e.ImageId).HasColumnName("image_id");
            entity.Property(e => e.Caption)
                .HasMaxLength(200)
                .HasColumnName("caption");
            entity.Property(e => e.Category).HasColumnName("category");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DisplayOrder)
                .HasDefaultValue(0)
                .HasColumnName("display_order");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("image_url");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Images)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__images__user_id__2739D489");
        });

        modelBuilder.Entity<Mission>(entity =>
        {
            entity.HasKey(e => e.MissionId).HasName("PK__mission__B5419AB28922714E");

            entity.ToTable("mission");

            entity.Property(e => e.MissionId).HasColumnName("mission_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.MissionDetail)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("mission_detail");
            entity.Property(e => e.MissionName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("mission_name");
            entity.Property(e => e.ResetType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("none")
                .HasColumnName("reset_type");
            entity.Property(e => e.RewardExp).HasColumnName("reward_exp");
            entity.Property(e => e.RewardPoints).HasColumnName("reward_points");
            entity.Property(e => e.TargetCount).HasColumnName("target_count");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("")
                .HasColumnName("target_type");
        });

        modelBuilder.Entity<MissionProgress>(entity =>
        {
            entity.HasKey(e => e.MissionProgressId).HasName("PK__mission___F43E603D4DB2CE0E");

            entity.ToTable("mission_progress");

            entity.HasIndex(e => new { e.UserId, e.MissionId }, "mission_progress_index_1").IsUnique();

            entity.Property(e => e.MissionProgressId).HasColumnName("mission_progress_id");
            entity.Property(e => e.AcceptedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("accepted_at");
            entity.Property(e => e.CompletedAt)
                .HasColumnType("datetime")
                .HasColumnName("completed_at");
            entity.Property(e => e.CurrentCount).HasColumnName("current_count");
            entity.Property(e => e.IsCompleted)
                .HasDefaultValueSql("('0')")
                .HasColumnName("is_completed");
            entity.Property(e => e.MissionId).HasColumnName("mission_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Mission).WithMany(p => p.MissionProgresses)
                .HasForeignKey(d => d.MissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mission_p__missi__2CF2ADDF");

            entity.HasOne(d => d.User).WithMany(p => p.MissionProgresses)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mission_p__user___31B762FC");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.MovieId).HasName("PK__movies__83CDF74926567634");

            entity.ToTable("movies");

            entity.Property(e => e.MovieId).HasColumnName("movie_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Director)
                .HasMaxLength(100)
                .HasColumnName("director");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.Genre)
                .HasMaxLength(100)
                .HasColumnName("genre");
            entity.Property(e => e.ImdbId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("imdb_id");
            entity.Property(e => e.OriginalTitle)
                .HasMaxLength(200)
                .HasColumnName("original_title");
            entity.Property(e => e.PosterUrl)
                .HasMaxLength(500)
                .HasColumnName("poster_url");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("rating");
            entity.Property(e => e.ReleaseDate).HasColumnName("release_date");
            entity.Property(e => e.Synopsis).HasColumnName("synopsis");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.TrailerUrl)
                .HasMaxLength(500)
                .HasColumnName("trailer_url");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<MovieReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__movie_re__60883D9059F97F9B");

            entity.ToTable("movie_reviews");

            entity.HasIndex(e => e.MovieId, "idx_movie");

            entity.HasIndex(e => e.OverallRating, "idx_rating");

            entity.HasIndex(e => e.UserId, "idx_user");

            entity.HasIndex(e => new { e.MovieId, e.UserId }, "movie_reviews_index_2").IsUnique();

            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.ActingRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("acting_rating");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.HelpfulCount)
                .HasDefaultValue(0)
                .HasColumnName("helpful_count");
            entity.Property(e => e.IsSpoiler)
                .HasDefaultValue(false)
                .HasColumnName("is_spoiler");
            entity.Property(e => e.LinkedPostId).HasColumnName("linked_post_id");
            entity.Property(e => e.MovieId).HasColumnName("movie_id");
            entity.Property(e => e.MusicRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("music_rating");
            entity.Property(e => e.OverallRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("overall_rating");
            entity.Property(e => e.StoryRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("story_rating");
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.ViewCount)
                .HasDefaultValue(0)
                .HasColumnName("view_count");
            entity.Property(e => e.VisualRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("visual_rating");

            entity.HasOne(d => d.LinkedPost).WithMany(p => p.MovieReviews)
                .HasForeignKey(d => d.LinkedPostId)
                .HasConstraintName("FK__movie_rev__linke__208CD6FA");

            entity.HasOne(d => d.Movie).WithMany(p => p.MovieReviews)
                .HasForeignKey(d => d.MovieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__movie_rev__movie__1F98B2C1");

            entity.HasOne(d => d.User).WithMany(p => p.MovieReviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__movie_rev__user___1EA48E88");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__order__46596229014D95EC");

            entity.ToTable("order");

            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Notes)
                .HasMaxLength(300)
                .HasColumnName("notes");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("order_date");
            entity.Property(e => e.RequiresShipping).HasColumnName("requires_shipping");
            entity.Property(e => e.TotalPrice).HasColumnName("total_price");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__user_id__3493CFA7");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__order_de__3C5A4080663AB9A6");

            entity.ToTable("order_detail");

            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.IsShipped).HasColumnName("is_shipped");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UnitPriceAtPurchase).HasColumnName("unit_price_at_purchase");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__order_det__order__3587F3E0");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_det__produ__367C1819");
        });

        modelBuilder.Entity<PointLog>(entity =>
        {
            entity.HasKey(e => e.PointLogId).HasName("PK__point_lo__E2EBFE7C152E2E06");

            entity.ToTable("point_log");

            entity.Property(e => e.PointLogId).HasColumnName("point_log_id");
            entity.Property(e => e.ChangeAmount).HasColumnName("change_amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasDefaultValue("unknow")
                .HasColumnName("description");
            entity.Property(e => e.PointTypeDefinitionId).HasColumnName("point_type_definition_id");
            entity.Property(e => e.SourceId).HasColumnName("source_id");
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("source_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.PointTypeDefinition).WithMany(p => p.PointLogs)
                .HasForeignKey(d => d.PointTypeDefinitionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__point_log__point__2EDAF651");

            entity.HasOne(d => d.User).WithMany(p => p.PointLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__point_log__user___2BFE89A6");
        });

        modelBuilder.Entity<PointPurchaseLog>(entity =>
        {
            entity.HasKey(e => e.PointPurchaseLogId).HasName("PK__point_pu__134871228085866B");

            entity.ToTable("point_purchase_log");

            entity.HasIndex(e => e.OrderNo, "UQ__point_pu__465C81B81B35C2DD").IsUnique();

            entity.Property(e => e.PointPurchaseLogId).HasColumnName("point_purchase_log_id");
            entity.Property(e => e.CashAmount)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("cash_amount");
            entity.Property(e => e.CompletedAt)
                .HasColumnType("datetime")
                .HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("order_no");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.PointsAmount).HasColumnName("points_amount");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.PointPurchaseLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__point_pur__user___2DE6D218");
        });

        modelBuilder.Entity<PointTypeDefinition>(entity =>
        {
            entity.HasKey(e => e.PointTypeDefinitionId).HasName("PK__point_ty__E69D541F8B2CA7DC");

            entity.ToTable("point_type_definition");

            entity.HasIndex(e => e.TypeName, "UQ__point_ty__543C4FD940BBCD54").IsUnique();

            entity.Property(e => e.PointTypeDefinitionId).HasColumnName("point_type_definition_id");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .HasColumnName("description");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type_name");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostsId).HasName("PK__posts__7F3EFABE1C8EE550");

            entity.ToTable("posts");

            entity.Property(e => e.PostsId).HasColumnName("posts_id");
            entity.Property(e => e.PostsContent)
                .IsRequired()
                .HasColumnName("posts_content");
            entity.Property(e => e.PostsCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("posts_created_at");
            entity.Property(e => e.PostsUpdatDate)
                .HasColumnType("datetime")
                .HasColumnName("posts_updat_date");
            entity.Property(e => e.PostsUserId).HasColumnName("posts_user_id");
            entity.Property(e => e.PostsViewCount)
                .HasDefaultValue(0)
                .HasColumnName("posts_view_count");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");

            entity.HasOne(d => d.PostsUser).WithMany(p => p.Posts)
                .HasForeignKey(d => d.PostsUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__posts__posts_use__3864608B");
        });

        modelBuilder.Entity<PostReplyLike>(entity =>
        {
            entity.HasKey(e => e.ReplyLikesId).HasName("PK__post_rep__BA01D0E784F6B6CC");

            entity.ToTable("post_reply_likes");

            entity.HasIndex(e => new { e.ReplyLikesId, e.ReplyLikesUserId }, "post_reply_likes_index_10").IsUnique();

            entity.Property(e => e.ReplyLikesId).HasColumnName("reply_likes_id");
            entity.Property(e => e.ReplyIkesId).HasColumnName("reply_ikes_id");
            entity.Property(e => e.ReplyLikesCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("reply_likes_created_at");
            entity.Property(e => e.ReplyLikesUserId).HasColumnName("reply_likes_user_id");

            entity.HasOne(d => d.ReplyIkes).WithMany(p => p.PostReplyLikes)
                .HasForeignKey(d => d.ReplyIkesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__post_repl__reply__40F9A68C");

            entity.HasOne(d => d.ReplyLikesUser).WithMany(p => p.PostReplyLikes)
                .HasForeignKey(d => d.ReplyLikesUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__post_repl__reply__3D2915A8");
        });

        modelBuilder.Entity<PostsLike>(entity =>
        {
            entity.HasKey(e => e.LikesId).HasName("PK__posts_li__0CA5EC54D5C208D2");

            entity.ToTable("posts_likes");

            entity.HasIndex(e => new { e.PostsLikesId, e.LikesUserId }, "posts_likes_index_9").IsUnique();

            entity.Property(e => e.LikesId).HasColumnName("likes_id");
            entity.Property(e => e.LikesCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("likes_created_at");
            entity.Property(e => e.LikesUserId).HasColumnName("likes_user_id");
            entity.Property(e => e.PostsLikesId).HasColumnName("posts_likes_id");

            entity.HasOne(d => d.LikesUser).WithMany(p => p.PostsLikes)
                .HasForeignKey(d => d.LikesUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__posts_lik__likes__3C34F16F");

            entity.HasOne(d => d.PostsLikes).WithMany(p => p.PostsLikes)
                .HasForeignKey(d => d.PostsLikesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__posts_lik__posts__40058253");
        });

        modelBuilder.Entity<PostsReply>(entity =>
        {
            entity.HasKey(e => e.ReplyId).HasName("PK__posts_re__EE405698AB031DA3");

            entity.ToTable("posts_replies");

            entity.Property(e => e.ReplyId).HasColumnName("reply_id");
            entity.Property(e => e.RepliesContent)
                .IsRequired()
                .HasColumnName("replies_content");
            entity.Property(e => e.RepliesCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("replies_created_at");
            entity.Property(e => e.RepliesPostId).HasColumnName("replies_post_id");
            entity.Property(e => e.RepliesUserId).HasColumnName("replies_user_id");
            entity.Property(e => e.TargetUserId).HasColumnName("target_user_id");

            entity.HasOne(d => d.RepliesPost).WithMany(p => p.PostsReplies)
                .HasForeignKey(d => d.RepliesPostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__posts_rep__repli__3F115E1A");

            entity.HasOne(d => d.RepliesUser).WithMany(p => p.PostsReplyRepliesUsers)
                .HasForeignKey(d => d.RepliesUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__posts_rep__repli__3A4CA8FD");

            entity.HasOne(d => d.TargetUser).WithMany(p => p.PostsReplyTargetUsers)
                .HasForeignKey(d => d.TargetUserId)
                .HasConstraintName("FK__posts_rep__targe__3B40CD36");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__product__47027DF5D3AE3345");

            entity.ToTable("product");

            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(300)
                .HasColumnName("description");
            entity.Property(e => e.ImageName)
                .HasMaxLength(50)
                .HasColumnName("image_name");
            entity.Property(e => e.IsOnSale)
                .HasDefaultValue(true)
                .HasColumnName("is_on_sale");
            entity.Property(e => e.IsPhysical).HasColumnName("is_physical");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Points).HasColumnName("points");
            entity.Property(e => e.Stock).HasColumnName("stock");
            entity.Property(e => e.Type)
                .HasMaxLength(30)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<ReviewHelpfulVote>(entity =>
        {
            entity.HasKey(e => e.VoteId).HasName("PK__review_h__9F5405AE9574994C");

            entity.ToTable("review_helpful_votes");

            entity.Property(e => e.VoteId).HasColumnName("vote_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.IsHelpful).HasColumnName("is_helpful");
            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.ReviewType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("review_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.ReviewHelpfulVotes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__review_he__user___245D67DE");
        });

        modelBuilder.Entity<SavePost>(entity =>
        {
            entity.HasKey(e => e.SaveId).HasName("PK__save_pos__319269DE7F623BE0");

            entity.ToTable("save_posts");

            entity.HasIndex(e => new { e.SaveUserId, e.SavePostsId }, "save_posts_index_8").IsUnique();

            entity.Property(e => e.SaveId).HasColumnName("save_id");
            entity.Property(e => e.SaveCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("save_created_at");
            entity.Property(e => e.SavePostsId).HasColumnName("save_posts_id");
            entity.Property(e => e.SaveUserId).HasColumnName("save_user_id");

            entity.HasOne(d => d.SavePosts).WithMany(p => p.SavePosts)
                .HasForeignKey(d => d.SavePostsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__save_post__save___3E1D39E1");

            entity.HasOne(d => d.SaveUser).WithMany(p => p.SavePosts)
                .HasForeignKey(d => d.SaveUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__save_post__save___395884C4");
        });

        modelBuilder.Entity<ShippedDetail>(entity =>
        {
            entity.HasKey(e => e.ShippedDetailId).HasName("PK__shipped___26C93C9342E38DFB");

            entity.ToTable("shipped_detail");

            entity.Property(e => e.ShippedDetailId).HasColumnName("shipped_detail_id");
            entity.Property(e => e.ArrivalDate)
                .HasColumnType("datetime")
                .HasColumnName("arrival_date");
            entity.Property(e => e.IsCompleted).HasColumnName("is_completed");
            entity.Property(e => e.OrderDetailId).HasColumnName("order_detail_id");
            entity.Property(e => e.RecipientAddress)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("recipient_address");
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("recipient_name");
            entity.Property(e => e.RecipientPhone)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("recipient_phone");
            entity.Property(e => e.ShippedDate)
                .HasColumnType("datetime")
                .HasColumnName("shipped_date");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.ShippedDetails)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__shipped_d__order__37703C52");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__user__B9BE370F6AA687F6");

            entity.ToTable("user");

            entity.HasIndex(e => e.Nickname, "UQ__user__5CF1C59B3264F725").IsUnique();

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Nickname)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nickname");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone).HasColumnName("phone");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("username");
        });

        modelBuilder.Entity<UserLogin>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("user_login");

            entity.Property(e => e.Loction)
                .HasMaxLength(255)
                .HasColumnName("loction");
            entity.Property(e => e.Logintime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("logintime");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__user_logi__user___2B0A656D");
        });

        modelBuilder.Entity<UserMovieList>(entity =>
        {
            entity.HasKey(e => e.ListId).HasName("PK__user_mov__7B9EF135F96DF46B");

            entity.ToTable("user_movie_list");

            entity.Property(e => e.ListId).HasColumnName("list_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.MovieId).HasColumnName("movie_id");
            entity.Property(e => e.PersonalRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("personal_rating");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.WatchDate).HasColumnName("watch_date");

            entity.HasOne(d => d.Movie).WithMany(p => p.UserMovieLists)
                .HasForeignKey(d => d.MovieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_movi__movie__2645B050");

            entity.HasOne(d => d.User).WithMany(p => p.UserMovieLists)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_movi__user___25518C17");
        });

        modelBuilder.Entity<UserStatus>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("user_status");

            entity.Property(e => e.Experience).HasColumnName("experience");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Rank).HasColumnName("rank");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__user_stat__user___2A164134");
        });

        modelBuilder.Entity<WalletTransaction>(entity =>
        {
            entity.HasKey(e => e.WalletTransactionsId).HasName("PK__wallet_t__54E8436663D419C3");

            entity.ToTable("wallet_transactions");

            entity.Property(e => e.WalletTransactionsId).HasColumnName("wallet_transactions_id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.RelatedOrderId)
                .HasMaxLength(100)
                .HasColumnName("related_order_id");
            entity.Property(e => e.TransactionStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("pending")
                .HasColumnName("transaction_status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.WalletTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__wallet_tr__user___2FCF1A8A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}