// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class MissionProgress
{
    public int MissionProgressId { get; set; }

    public int UserId { get; set; }

    public int MissionId { get; set; }

    public int CurrentCount { get; set; }

    public bool? IsCompleted { get; set; }

    public DateTime? AcceptedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Mission Mission { get; set; }

    public virtual User User { get; set; }
}