// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Mission
{
    public int MissionId { get; set; }

    public string MissionName { get; set; }

    public string MissionDetail { get; set; }

    public string TargetType { get; set; }

    public int TargetCount { get; set; }

    public int RewardPoints { get; set; }

    public int RewardExp { get; set; }

    public string ResetType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<MissionProgress> MissionProgresses { get; set; } = new List<MissionProgress>();
}