// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class MovieReview
{
    public int ReviewId { get; set; }

    public int MovieId { get; set; }

    public int UserId { get; set; }

    public decimal OverallRating { get; set; }

    public decimal? StoryRating { get; set; }

    public decimal? ActingRating { get; set; }

    public decimal? VisualRating { get; set; }

    public decimal? MusicRating { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public bool? IsSpoiler { get; set; }

    public int? HelpfulCount { get; set; }

    public int? ViewCount { get; set; }

    public int? LinkedPostId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Post LinkedPost { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}