// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Title { get; set; }

    public string OriginalTitle { get; set; }

    public string Director { get; set; }

    public string Genre { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public int? Duration { get; set; }

    public decimal? Rating { get; set; }

    public string PosterUrl { get; set; }

    public string Synopsis { get; set; }

    public string TrailerUrl { get; set; }

    public string ImdbId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<MovieReview> MovieReviews { get; set; } = new List<MovieReview>();

    public virtual ICollection<UserMovieList> UserMovieLists { get; set; } = new List<UserMovieList>();
}