// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public int TotalPrice { get; set; }

    public DateTime OrderDate { get; set; }

    public bool RequiresShipping { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual User User { get; set; }
}