// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PointTypeDefinition
{
    public int PointTypeDefinitionId { get; set; }

    public string TypeName { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<PointLog> PointLogs { get; set; } = new List<PointLog>();
}