// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PointPurchaseLog
{
    public int PointPurchaseLogId { get; set; }

    public int UserId { get; set; }

    public string OrderNo { get; set; }

    public decimal CashAmount { get; set; }

    public int PointsAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual User User { get; set; }
}