// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PointLog
{
    public int PointLogId { get; set; }

    public int UserId { get; set; }

    public string SourceType { get; set; }

    public int SourceId { get; set; }

    public int PointTypeDefinitionId { get; set; }

    public int ChangeAmount { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual PointTypeDefinition PointTypeDefinition { get; set; }

    public virtual User User { get; set; }
}