// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PostsReply
{
    public int ReplyId { get; set; }

    public int RepliesPostId { get; set; }

    public int RepliesUserId { get; set; }

    public string RepliesContent { get; set; }

    public int? TargetUserId { get; set; }

    public DateTime? RepliesCreatedAt { get; set; }

    public virtual ICollection<PostReplyLike> PostReplyLikes { get; set; } = new List<PostReplyLike>();

    public virtual Post RepliesPost { get; set; }

    public virtual User RepliesUser { get; set; }

    public virtual User TargetUser { get; set; }
}