// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PostsLike
{
    public int LikesId { get; set; }

    public int PostsLikesId { get; set; }

    public int LikesUserId { get; set; }

    public DateTime? LikesCreatedAt { get; set; }

    public virtual User LikesUser { get; set; }

    public virtual Post PostsLikes { get; set; }
}