// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class Post
{
    public int PostsId { get; set; }

    public int PostsUserId { get; set; }

    public string Title { get; set; }

    public string PostsContent { get; set; }

    public int? PostsViewCount { get; set; }

    public DateTime? PostsCreatedAt { get; set; }

    public DateTime? PostsUpdatDate { get; set; }

    public bool IsCommission { get; set; }

    public virtual ICollection<CinemaReview> CinemaReviews { get; set; } = new List<CinemaReview>();

    public virtual ICollection<MovieReview> MovieReviews { get; set; } = new List<MovieReview>();

    public virtual ICollection<PostsLike> PostsLikes { get; set; } = new List<PostsLike>();

    public virtual ICollection<PostsReply> PostsReplies { get; set; } = new List<PostsReply>();

    public virtual User PostsUser { get; set; }

    public virtual ICollection<SavePost> SavePosts { get; set; } = new List<SavePost>();
}