// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class PostReplyLike
{
    public int ReplyLikesId { get; set; }

    public int ReplyIkesId { get; set; }

    public int ReplyLikesUserId { get; set; }

    public DateTime? ReplyLikesCreatedAt { get; set; }

    public virtual PostsReply ReplyIkes { get; set; }

    public virtual User ReplyLikesUser { get; set; }
}