// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class ReviewHelpfulVote
{
    public int VoteId { get; set; }

    public string ReviewType { get; set; }

    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public bool IsHelpful { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}