// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class SavePost
{
    public int SaveId { get; set; }

    public int SaveUserId { get; set; }

    public int SavePostsId { get; set; }

    public DateTime? SaveCreatedAt { get; set; }

    public virtual Post SavePosts { get; set; }

    public virtual User SaveUser { get; set; }
}