// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class ShippedDetail
{
    public int ShippedDetailId { get; set; }

    public int OrderDetailId { get; set; }

    public string RecipientName { get; set; }

    public string RecipientAddress { get; set; }

    public string RecipientPhone { get; set; }

    public DateTime? ShippedDate { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public bool IsCompleted { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}