// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class UserStatus
{
    public int? UserId { get; set; }

    public int? Experience { get; set; }

    public int? Rank { get; set; }

    public int? ItemId { get; set; }

    public int? Quantity { get; set; }

    public virtual User User { get; set; }
}