// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class UserMovieList
{
    public int ListId { get; set; }

    public int UserId { get; set; }

    public int MovieId { get; set; }

    public string Status { get; set; }

    public DateOnly? WatchDate { get; set; }

    public decimal? PersonalRating { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}