// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Nickname { get; set; }

    public string Password { get; set; }

    public int? Phone { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CinemaReview> CinemaReviews { get; set; } = new List<CinemaReview>();

    public virtual ICollection<EntrustMissionProgress> EntrustMissionProgresses { get; set; } = new List<EntrustMissionProgress>();

    public virtual ICollection<EntrustMission> EntrustMissions { get; set; } = new List<EntrustMission>();

    public virtual ICollection<Follow> FollowFollowees { get; set; } = new List<Follow>();

    public virtual ICollection<Follow> FollowFollowers { get; set; } = new List<Follow>();

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<MissionProgress> MissionProgresses { get; set; } = new List<MissionProgress>();

    public virtual ICollection<MovieReview> MovieReviews { get; set; } = new List<MovieReview>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PointLog> PointLogs { get; set; } = new List<PointLog>();

    public virtual ICollection<PointPurchaseLog> PointPurchaseLogs { get; set; } = new List<PointPurchaseLog>();

    public virtual ICollection<PostReplyLike> PostReplyLikes { get; set; } = new List<PostReplyLike>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<PostsLike> PostsLikes { get; set; } = new List<PostsLike>();

    public virtual ICollection<PostsReply> PostsReplyRepliesUsers { get; set; } = new List<PostsReply>();

    public virtual ICollection<PostsReply> PostsReplyTargetUsers { get; set; } = new List<PostsReply>();

    public virtual ICollection<ReviewHelpfulVote> ReviewHelpfulVotes { get; set; } = new List<ReviewHelpfulVote>();

    public virtual ICollection<SavePost> SavePosts { get; set; } = new List<SavePost>();

    public virtual ICollection<UserMovieList> UserMovieLists { get; set; } = new List<UserMovieList>();

    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}