// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class UserLogin
{
    public int? UserId { get; set; }

    public DateTime? Logintime { get; set; }

    public string Loction { get; set; }

    public virtual User User { get; set; }
}