// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace incode.Models;

public partial class WalletTransaction
{
    public int WalletTransactionsId { get; set; }

    public int UserId { get; set; }

    public decimal Amount { get; set; }

    public string TransactionStatus { get; set; }

    public string RelatedOrderId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}